[package]
name = "fractal-rendering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ravif = "0.8.8"
clap = "^3"
rayon = "^1.5"
rand = { version = "0.8.4", features = ["small_rng"] }
